### ISSUE TITLE
NPE on export calendar events without description

### ISSUE THREAD

**Issue by fabiopezzutto** [smclab/caldav-sync#61]
Line https://github.com/smclab/caldav-sync/blob/58-porting_issue_57/modules/caldav-sync/caldav-sync-web/src/main/java/it/smc/calendar/caldav/sync/listener/DefaultICSContentListener.java#L532 throws a NPE when description in empty

```
com.liferay.portal.kernel.sanitizer.SanitizerException: java.lang.NullPointerException
	at it.smc.calendar.caldav.sync.listener.DefaultICSContentListener.beforeContentImported(DefaultICSContentListener.java:308)
	at it.smc.calendar.caldav.sync.LiferayCalDAVStorageImpl.putResource(LiferayCalDAVStorageImpl.java:431)
	at it.smc.calendar.caldav.sync.methods.PutMethodImpl.process(PutMethodImpl.java:31)
	at com.liferay.portal.webdav.WebDAVServlet.service(WebDAVServlet.java:122)
. . .
Caused by: java.lang.NullPointerException
	at it.smc.calendar.caldav.sync.listener.DefaultICSContentListener.updateAltDescription(DefaultICSContentListener.java:536)
	at it.smc.calendar.caldav.sync.listener.DefaultICSContentListener.beforeContentImported(DefaultICSContentListener.java:293)
	... 65 more
```

**Comment by domenicocosta** [comment]
#close merged from branch 61 to 4.0.x
